#!/bin/bash

printf "                         _                 \n"
printf "           __ _ _ __ ___| |__   ___  _ __  \n"
printf "          / _' | '__|_  / '_ \ / _ \| '_ \ \n"
printf "         | (_| | |   / /| | | | (_) | | | |\n"
printf "          \__,_|_|  /___|_| |_|\___/|_| |_|\n"
printf "\n"
printf " Virtual Private Server Owned by William Chanrico\n"
